import { DMMF } from "@prisma/generator-helper";
import { autoGeneratedMessage } from "./dto_template";

type Data = {
  enums: DMMF.DatamodelEnum[];
};

export const registerEnumsTemplate = (clientPath: string, data: Data) => `
${autoGeneratedMessage}

import { registerEnumType } from "@nestjs/graphql"; 
import { ${data.enums.map(e => e.name)} } from "${clientPath}";

export function registerEnums() {
  ${data.enums
    .map(
      e => `registerEnumType(${e.name}, {
    name: '${e.name}',
  });`,
    )
    .join("")}
}
`;
