export const GENERATOR_NAME = "prisma-generator-nestjs-graphql";

export const AUTO_GENERATED_MESSAGE = `
/////////////////////////////////////
// THIS FILE WAS AUTO GENERATED
// DO NOT EDIT THIS FILE DIRECTLY
/////////////////////////////////////
`;

export type ModelOptions = {
  clientPath: string;
  prefix: string;
  abstract: boolean;
};
